-- UIParent
-- A parent frame for all of the frames generated by the addon
local AddonName, Addon = ...

-- Using SecureHandlerAttributeTemplate so that we can eventually handle global state changes (like the override and pet
-- battle UIs) in a single place
local UIParent = CreateFrame("Frame", ("%sUIParent"):format(AddonName), _G.UIParent, "SecureHandlerAttributeTemplate")

UIParent:SetAllPoints(UIParent:GetParent())

Addon.UIParent = UIParent